<?php
/**
 * Created By : RH
 */
?>
<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="in_categories" data-form-part="category_form" id="in_categories" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "Zestardtech_Categorytree/js/assign_category": {
                "selectedCategories":  <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>